#!/bin/bash
set -euo pipefail

# ==============================================================================
# 🚀 自动化集群启动脚本 (Auto-generated by AI Assistant)
# 功能：
# 1. 自动读取节点列表 (node_list.txt)
# 2. 在所有节点并行拉起/检查 Docker 容器 (调用 start_docker_image.sh)
# 3. 启动分布式训练任务 (调用 launch_multi_nodes_full.sh)
# ==============================================================================

# --- 全局配置 ---
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$(dirname "$SCRIPT_DIR")")" # 假设 scripts/docker_cluster/run.sh -> 项目根目录

# 默认节点列表文件 (优先当前目录，其次是项目根目录)
if [[ -f "${SCRIPT_DIR}/node_list.txt" ]]; then
    NODE_LIST_FILE="${SCRIPT_DIR}/node_list.txt"
elif [[ -f "${PROJECT_ROOT}/node_list.txt" ]]; then
    NODE_LIST_FILE="${PROJECT_ROOT}/node_list.txt"
else
    # 如果都找不到，创建一个示例并退出
    echo "⚠️  未找到 node_list.txt, 正在当前目录创建示例..."
    echo "192.168.1.101" > "${SCRIPT_DIR}/node_list.txt"
    echo "192.168.1.102" >> "${SCRIPT_DIR}/node_list.txt"
    echo "❌ 请编辑 ${SCRIPT_DIR}/node_list.txt 填入实际节点 IP 后再次运行。"
    exit 1
fi

# 关键脚本路径
START_DOCKER_SCRIPT="${SCRIPT_DIR}/start_docker_image.sh"
LAUNCH_TRAIN_SCRIPT="${SCRIPT_DIR}/launch_multi_nodes_full.sh"

# --- Docker 环境变量配置 ---
# 请根据实际环境修改这些值，或者通过外部环境变量传入
export IMAGE_NAME="${IMAGE_NAME:-cis-pengcheng.cmecloud.cn/ascendhub/mindspeed-llm}"
export IMAGE_TAG="${IMAGE_TAG:-openeuler22.03-mindspeed-llm-2.3.0-a3-arm}"
export CONTAINER_NAME="${CONTAINER_NAME:-mindspeed-llm-env}"
export IMAGE_PATH="${IMAGE_PATH:-/llm_workspace_1P/robin/mindspeed-llm-2.3.0-a3-arm.tarr}"
export NPUS="${NPUS:-0,1,2,3,4,5,6,7}"
export SHARE_PATH_HOST="${SHARE_PATH_HOST:-/llm_workspace_1P/robin}"
export SHARE_PATH_CONTAINER="${SHARE_PATH_CONTAINER:-/llm_workspace_1P/robin}"

# --- 日志函数 ---
log() {
    echo -e "$(date +'%Y-%m-%d %H:%M:%S') [$1] $2"
}

# ==============================================================================
# 1. 解析节点列表
# ==============================================================================
log "INFO" "正在读取节点列表: $NODE_LIST_FILE"
mapfile -t NODE_HOSTS < <(grep -v -e '^\s*$' -e '^\s*#' "$NODE_LIST_FILE")
NODE_COUNT=${#NODE_HOSTS[@]}

if [ "$NODE_COUNT" -eq 0 ]; then
    log "ERROR" "节点列表为空！"
    exit 1
fi
log "INFO" "共发现 $NODE_COUNT 个节点: ${NODE_HOSTS[*]}"

# ==============================================================================
# 2. 并行启动 Docker 容器
# ==============================================================================
log "INFO" "🚀 [Step 1] 开始在所有节点启动 Docker 容器..."

PIDS=()
for node in "${NODE_HOSTS[@]}"; do
    (
        log "INFO" "  -> 正在处理节点: $node"
        
        # 2.1 创建远程临时目录
        ssh -o StrictHostKeyChecking=no "$node" "mkdir -p /tmp/k8s_cluster_scripts"
        
        # 2.2 传输启动脚本
        if ! scp -o StrictHostKeyChecking=no "$START_DOCKER_SCRIPT" "$node:/tmp/k8s_cluster_scripts/start_docker_image.sh"; then
            log "ERROR" "  -> [Failed] 无法拷贝脚本到节点 $node"
            exit 1
        fi
        
        # 2.3 远程执行启动脚本
        # 使用 EOF 块传递环境变量并执行
        ssh -o StrictHostKeyChecking=no "$node" "bash -s" <<EOF
            export IMAGE_NAME='$IMAGE_NAME'
            export IMAGE_TAG='$IMAGE_TAG'
            export CONTAINER_NAME='$CONTAINER_NAME'
            export IMAGE_PATH='$IMAGE_PATH'
            export NPUS='$NPUS'
            export SHARE_PATH_HOST='$SHARE_PATH_HOST'
            export SHARE_PATH_CONTAINER='$SHARE_PATH_CONTAINER'
            
            # 加载并执行 start_docker 函数
            source /tmp/k8s_cluster_scripts/start_docker_image.sh
            start_docker
EOF
        
        if [ $? -eq 0 ]; then
            log "INFO" "  -> [Success] 节点 $node Docker 容器就绪"
        else
            log "ERROR" "  -> [Failed] 节点 $node 启动 Docker 失败"
            exit 1
        fi
    ) &
    PIDS+=($!)
done

# 等待所有子进程完成
FAIL=0
for pid in "${PIDS[@]}"; do
    wait "$pid" || FAIL=1
done

if [ "$FAIL" -ne 0 ]; then
    log "ERROR" "部分节点 Docker 启动失败，请检查日志。终止后续任务。"
    exit 1
fi

log "INFO" "✅ [Step 1] 所有节点 Docker 容器已准备就绪。"

# ==============================================================================
# 3. 启动分布式训练
# ==============================================================================
log "INFO" "🚀 [Step 2] 启动分布式训练任务..."

if [[ ! -f "$LAUNCH_TRAIN_SCRIPT" ]]; then
    log "ERROR" "训练启动脚本未找到: $LAUNCH_TRAIN_SCRIPT"
    exit 1
fi

# 调用 launch_multi_nodes_full.sh 并传递节点列表文件
bash "$LAUNCH_TRAIN_SCRIPT" "$NODE_LIST_FILE"
