apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        fdd-label: "full-super-node"
      containers:
      - name: nginx
        image: cis-pengcheng.cmecloud.cn/ascendhub/mindspeed-llm:openeuler22.03-mindspeed-llm-2.3.0-a3-arm-custom-v3.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
