apiVersion: v1
kind: ConfigMap
metadata:
  name: reset-config-robin-llama31-503b-128-nodes # The value of JobName must be the same as the name attribute of the following job. The prefix fault-config- cannot be modified.
  namespace: default # Name Space must be set to "default"
  labels:
    reset: "true"
data:
  reset.json: |
    {
        "status":"initializing"
    }
  checkCode: ""
---
apiVersion: mindxdl.gitee.com/v1
kind: AscendJob
metadata:
  name: robin-llama31-503b-128-nodes
  labels:
    framework: pytorch
    ring-controller.atlas: ascend-910b
    tor-affinity: "null" #该标签为任务是否使用交换机亲和性调度标签，null或者不写该标签则不适用。large-model-schema表示大模型任务，normal-schema 普通任务
    fault-scheduling: "force"
    fault-retry-times: "1"
    pod-rescheduling: "on" # 开启pod重调度
    process-recover-enable: "on" # 开启训练进程级恢复
    subHealthyStrategy: "ignore" # 忽略亚健康
  annotations:
    sp-block: "128"
    huawei.com/schedule_policy: chip2-node8-sp
    wait-reschedule-timeout: "270" # 进程级恢复等待故障节点重调度的超时时间，默认270秒，取值范围30-270。进程级恢复和弹性训练均开启时，则等待此时间后若故障节点调度成功，则进行进程级恢复，否则触发弹性训练
    recover-strategy: "retry,recover,dump,exit,elastic-training" # 开启step重计算、进程级恢复、临终遗言、进程退出和弹性训练
spec:
  schedulerName: volcano # work when enableGangScheduling is true
  runPolicy:
    schedulingPolicy: # work when enableGangScheduling is true
      minAvailable: 16
      queue: default
  successPolicy: AllWorkers
  replicaSpecs:
    Master:
      replicas: 1
      restartPolicy: Never
      template:
        metadata:
          labels:
            ring-controller.atlas: ascend-910b
        spec:
          terminationGracePeriodSeconds: 30
          automountServiceAccountToken: false
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: job-name
                        operator: In
                        values:
                          - robin-llama31-503b-128-nodes
                  topologyKey: kubernetes.io/hostname
          nodeSelector:
            ascend/train.nums: "1024"
            host-arch: huawei-arm
            accelerator-type: module-a3-8-super-pod # depend on your device model, 910bx8 is module-910b-8 ,910bx16 is module-910b-16
          hostNetwork: true
          containers:
            - name: ascend # do not modify
              image: cis-pengcheng.cmecloud.cn/ascendhub/mindspeed-llm:openeuler22.03-mindspeed-llm-2.3.0-a3-arm # trainning framework image， which can be modified
              imagePullPolicy: IfNotPresent
              env:
                - name: LD_LIBRARY_PATH
                  value: "/usr/local/Ascend/driver/lib64/common:/usr/local/Ascend/driver/lib64/driver:/usr/local/Ascend/driver/lib64:${LD_LIBRARY_PATH}"
                - name: XDL_IP # IP address of the physical node, which is used to identify the node where the pod is running
                  valueFrom:
                    fieldRef:
                      fieldPath: status.hostIP
                # ASCEND_VISIBLE_DEVICES env variable is used by ascend-docker-runtime when in the whole card scheduling scene with volcano scheduler.
                # Please delete it when in the static vNPU scheduling, dynamic vNPU scheduling, volcano without Ascend-volcano-plugin, without volcano scenes.
                - name: ASCEND_VISIBLE_DEVICES
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['huawei.com/Ascend910'] # The value must be the same as resources.requests
                - name: TTP_PORT # 用于mindio通信，请注意上下保持一致
                  value: "8000"
                - name: PROCESS_RECOVER # 开启进程级别重调度需注入该环境变量
                  value: "on"
                - name: MINDIO_WAIT_MINDX_TIME # mindio暂停训练后等待恢复策略下发时间，未开启进程级重调度，开启弹性训练场景下，建议配置60及以上
                  value: "60"
                - name: POD_IP
                  valueFrom:
                    fieldRef:
                      fieldPath: status.podIP
              command: # training command, which can be modified
                - /bin/bash
                - -c
              args:
                - |
                  cd /job/code;
                  chmod +x scripts/k8s_pretrain_llama31_503b_4k_A3_ptd.sh;
                  bash scripts/k8s_pretrain_llama31_503b_4k_A3_ptd.sh
              ports: # default value containerPort: 2222 name: ascendjob-port if not set
                - containerPort: 2222 # determined by user
                  name: ascendjob-port # do not modify
                - containerPort: 8000 # 用于mindio通信，请注意上下保持一致
                  name: ttp-port
                - containerPort: 9601 # 用于taskd通信，请注意上下保持一致
                  name: taskd-port
              resources:
                limits:
                  huawei.com/Ascend910: 8
                requests:
                  huawei.com/Ascend910: 8
              volumeMounts:
                - name: code
                  mountPath: /job/code
                - name: data
                  mountPath: /job/data
                - name: ascend-driver
                  mountPath: /usr/local/Ascend/driver
                - name: dshm
                  mountPath: /dev/shm
                - name: localtime
                  mountPath: /etc/localtime
                - name: reset-config
                  mountPath: /user/restore/reset/config
                  readOnly: true
                - name: ranktable # if ranktable is needed please set volume
                  mountPath: /user/serverid/devindex/config
          volumes:
            - name: reset-config
              hostPath:
                path: /user/restore/reset/default.reset-config-robin-llama31-503b-128-nodes # Correspond to the /user/restore/reset/namespace.configmap-name above.
            - name: code
              hostPath:
                path: /llm_workspace_1P/robin/MindSpeed-LLM
            - name: data
              hostPath:
                path: /llm_workspace_1P/robin/hfhub/
            - name: ascend-driver
              hostPath:
                path: /usr/local/Ascend/driver
            - name: dshm
              emptyDir:
                medium: Memory
            - name: localtime
              hostPath:
                path: /etc/localtime
            - name: ranktable
              hostPath:
                path: /llm_workspace_1P/ranktable/default.robin-llama31-503b-128-nodes # need pattern: shared-dir/job-namespace.job-name, the shared-dir should share with ascend-operator
                type: Directory
    Worker:
      replicas: 127
      restartPolicy: Never
      template:
        metadata:
          labels:
            ring-controller.atlas: ascend-910b
        spec:
          terminationGracePeriodSeconds: 10
          automountServiceAccountToken: false
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: job-name
                        operator: In
                        values:
                          - robin-llama31-503b-128-nodes
                  topologyKey: kubernetes.io/hostname
          nodeSelector:
            ascend/train.nums: "1024"
            host-arch: huawei-arm
            accelerator-type: module-a3-8-super-pod # depend on your device model, 910bx8 is module-910b-8 ,910bx16 is module-910b-16
          hostNetwork: true
          containers:
            - name: ascend # do not modify
              image: cis-pengcheng.cmecloud.cn/ascendhub/mindspeed-llm:openeuler22.03-mindspeed-llm-2.3.0-a3-arm # trainning framework image， which can be modified
              imagePullPolicy: IfNotPresent
              env:
                - name: LD_LIBRARY_PATH
                  value: "/usr/local/Ascend/driver/lib64/common:/usr/local/Ascend/driver/lib64/driver:/usr/local/Ascend/driver/lib64:${LD_LIBRARY_PATH}"
                - name: XDL_IP # IP address of the physical node, which is used to identify the node where the pod is running
                  valueFrom:
                    fieldRef:
                      fieldPath: status.hostIP
                # ASCEND_VISIBLE_DEVICES env variable is used by ascend-docker-runtime when in the whole card scheduling scene with volcano scheduler.
                # Please delete it when in the static vNPU scheduling, dynamic vNPU scheduling, volcano without Ascend-volcano-plugin, without volcano scenes.
                - name: ASCEND_VISIBLE_DEVICES
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['huawei.com/Ascend910'] # The value must be the same as resources.requests
                - name: TTP_PORT # 用于mindio通信，请注意上下保持一致
                  value: "8000"
                - name: PROCESS_RECOVER # 开启进程级别重调度需注入该环境变量
                  value: "on"
                - name: MINDIO_WAIT_MINDX_TIME # mindio暂停训练后等待恢复策略下发时间，未开启进程级重调度，开启弹性训练场景下，建议配置60及以上
                  value: "60"
                - name: POD_IP
                  valueFrom:
                    fieldRef:
                      fieldPath: status.podIP
              command: # training command, which can be modified
                - /bin/bash
                - -c
              args:
                - |
                  cd /job/code;
                  chmod +x scripts/k8s_pretrain_llama31_503b_4k_A3_ptd.sh;
                  bash scripts/k8s_pretrain_llama31_503b_4k_A3_ptd.sh
              ports: # default value containerPort: 2222 name: ascendjob-port if not set
                - containerPort: 2222 # determined by user
                  name: ascendjob-port # do not modify
                - containerPort: 8000 # 用于mindio通信，请注意上下保持一致
                  name: ttp-port
                - containerPort: 9601 # 用于taskd通信，请注意上下保持一致
                  name: taskd-port
              resources:
                limits:
                  huawei.com/Ascend910: 8
                requests:
                  huawei.com/Ascend910: 8
              volumeMounts:
                - name: code
                  mountPath: /job/code
                - name: data
                  mountPath: /job/data
                - name: ascend-driver
                  mountPath: /usr/local/Ascend/driver
                - name: dshm
                  mountPath: /dev/shm
                - name: localtime
                  mountPath: /etc/localtime
                - name: reset-config
                  mountPath: /user/restore/reset/config
                  readOnly: true
                - name: ranktable # if ranktable is needed please set volume
                  mountPath: /user/serverid/devindex/config
          volumes:
            - name: reset-config
              hostPath:
                path: /user/restore/reset/default.reset-config-robin-llama31-503b-128-nodes # Correspond to the /user/restore/reset/namespace.configmap-name above.
            - name: code
              hostPath:
                path: /llm_workspace_1P/robin/MindSpeed-LLM
            - name: data
              hostPath:
                path: /llm_workspace_1P/robin/hfhub/
            - name: ascend-driver
              hostPath:
                path: /usr/local/Ascend/driver
            - name: dshm
              emptyDir:
                medium: Memory
            - name: localtime
              hostPath:
                path: /etc/localtime
            - name: ranktable
              hostPath:
                path: /llm_workspace_1P/ranktable/default.robin-llama31-503b-128-nodes # need pattern: shared-dir/job-namespace.job-name, the shared-dir should share with ascend-operator
                type: Directory
